const {chromium}=require('C:/Users/Abdalrahman/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert/strict');
const fs=require('fs');
const path=require('path');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:375,height:812}});
  const page=await context.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:5182/#/market',{waitUntil:'domcontentloaded'});
  await page.locator('article').first().waitFor();
  await page.waitForTimeout(13000);
  const cardsBefore=await page.locator('article').allInnerTexts();
  const datesBefore=await page.getByText(/آخر تحقق:/).allTextContents();
  await context.setOffline(true);
  await page.getByRole('button',{name:'التحقق من أحدث البيانات الرسمية',exact:true}).click();
  await page.getByRole('status').filter({hasText:'تعذّر التحقق'}).waitFor();
  assert.deepEqual(await page.locator('article').allInnerTexts(),cardsBefore);
  assert.deepEqual(await page.getByText(/آخر تحقق:/).allTextContents(),datesBefore);
  await page.getByRole('button',{name:'الدليل',exact:true}).click();
  await page.getByLabel('ابحث في الدليل').fill('الطب');
  assert.equal(await page.locator('article').count(),1);
  await page.locator('h1').first().click();
  await page.getByRole('button',{name:'ملفّي',exact:true}).click();
  await page.getByLabel('الاسم المفضل (اختياري)').fill('محلي دون اتصال');
  await page.getByRole('button',{name:'حفظ على هذا الجهاز'}).click();
  await page.getByRole('status').filter({hasText:'حُفظ ملفك'}).waitFor();
  assert.deepEqual(errors,[]);
  const blocked=await browser.newContext();
  await blocked.addInitScript(()=>{
    Object.defineProperty(Storage.prototype,'getItem',{value:()=>{throw new DOMException('Blocked','SecurityError')}});
    Object.defineProperty(Storage.prototype,'setItem',{value:()=>{throw new DOMException('Blocked','QuotaExceededError')}});
  });
  const blockedPage=await blocked.newPage();
  blockedPage.on('pageerror',e=>errors.push(e.message));
  await blockedPage.goto('http://127.0.0.1:5182/#/profile',{waitUntil:'domcontentloaded'});
  await blockedPage.getByLabel('الاسم المفضل (اختياري)').fill('بيانات محفوظة في الحقل');
  await blockedPage.getByRole('button',{name:'حفظ على هذا الجهاز'}).click();
  await blockedPage.getByRole('status').filter({hasText:'تعذّر الحفظ'}).waitFor();
  assert.equal(await blockedPage.getByLabel('الاسم المفضل (اختياري)').inputValue(),'بيانات محفوظة في الحقل');
  assert.deepEqual(errors,[]);
  const result={offlineOpenApp:'PASS',indicatorsPreserved:cardsBefore,timestampsPreserved:datesBefore,offlineGuide:'PASS',offlineProfile:'PASS',blockedStorageGraceful:'PASS',errors};
  fs.writeFileSync(path.join(__dirname,'offline-audit.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result,null,2));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
